### PR TITLE
serve d3 locally and get force-graphs to version 1 status

### PR DESCRIPTION
**Pull request by knappa**

### CODE REVIEW

**Comment by chifman** [comment]
“find all fixed points” still does not work.

I have noticed that m2 was outside of the folder “steady_cell_phenotype” in previous version not it is inside. Could that be a problem? It does not know where to find m2 file?

From: Adam Knapp ***@***.***>
Date: Wednesday, April 7, 2021 at 5:11 PM
To: knappa/steadycellphenotype ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [knappa/steadycellphenotype] serve d3 locally and get force-graphs to version 1 status (#5)

External Email: Use caution with links and attachments.

Merged #5<https://urldefense.com/v3/__https:/github.com/knappa/steadycellphenotype/pull/5__;!!IaT_gp1N!mmugoHT-nMqgjScY8zB1oTfNxDW2hZhkmvUc6VsoD45BzNvAKjt7mht5ThkI5vKZkA$> into master.

**Comment by chifman** [comment]
the graphs work well. One issue: some graphs do not fit the window. Anyway to make sure window is adjusted based on the size of the graph?

**Comment by chifman** [comment]
Also, should we allow users to save a static image ones they are satisfied with the graph?

**Comment by knappa** [comment]
Note to future self: problem with find all fixed points was solved by a forced reinstall.

**Pull request merged**
